### ISSUE TITLE
Разбираться с компиляцией QT Creator

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/ImageView#3]

**Comment by Beozar** [comment]
Пока я пытаюсь нарастить жир, отрастить бороду и разобраться как нормально поставить второй системой арч, мы на компе бороды скомпилили Qt. По крайней мере компилится уже минут 20 и вылетать не намерено. Вот она, сила Macbook Air 13. На правах рекламы, мне дадут за это скидку в apple.store?

**Comment by Sovent** [comment]
Для индульгенции от Apple тебе потребуется предпринять действия более интимного характера. Закрывай задачу, когда она закрыта, а не когда кажется, что закрыта.

**Comment by Beozar** [comment]
Есть, шеф.
