### ISSUE TITLE
Разобраться, делать плагин отдельным окном или встроенным в QT

### ISSUE THREAD

**Issue by Sovent** [LeagueOfDevelopers/ImageView#4]
Максим

**Comment by Beozar** [comment]
Ну что, мысли пока такие. Сейчас сделаю встроенный плагин в QT по мануалам, суть такая. Так скажем "встроенный отладчик" в QT это граф интерфейс, суть которого в том, что через обертку он через стандартный поток ввода-вывода работает с gdb. Итак,  задачу разбиваем на подпункты.
а) Сделать просто пустое отдельное окно под наше приложение
б) Разобраться с тем, как достучаться до того процесса, который отвечает за диалог с gdb и вытащить оттуда ссылку на интересующую нас переменную.
в) Подключить какую-нибудь граф библиотеку (opencv, как вариант) и отобразить какой-нибудь простой bmp-шник  в нашем окне.альше посмотрим.
Меня начинают грызть сомнения не может ли случаем адрес у объекта меняться самопроизвольно на протяжении кода. Сейчас обратился за консультацией, ждем-с ответа.
проблема №2: я пока без понятия как реализовать locals грамотно.(да и данный watches тоже на костыль похож)

**Comment by Sovent** [comment]
Склонен считать, что у объекта не может самопроизвольно меняться адрес. 
Для Locals должно быть какое-нибудь элегантное решение, если его нет и нужно будет костылировать, оставьте эту проблему на попозже.

**Comment by Sovent** [comment]
А план хорош
